# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pyRevit blog
email: eirannejad@gmail.com

# this means to ignore newlines until "baseurl:"
description: >
  python Rapid Application Development (RAD) Environment for Autodesk Revit®

# the subpath of your site, e.g. /blog
baseurl: "/pyRevit"

# the base hostname & protocol for your site
url: "https://eirannejad.github.io"

twitter:
  username: eirannejad
github_username:  eirannejad

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins_dir:
  - jekyll-seo-tag
